sudo: required
language: r
warnings_are_errors: false
dist: trusty

r_packages:
  - testthat
  - covr

r_github_packages:
  - greta-dev/greta

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - libmagick++-dev
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - python-dev
      - libv8-dev

before_install:
  - python -m pip install --user --upgrade pip
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user 'tensorflow==1.12'
  - pip install --user --upgrade tensorflow-probability
  
after_success:
  - Rscript -e "covr::codecov()"

email:
  on_success: change
  on_failure: change
