sudo: required
language: r
warnings_are_errors: false
dist: trusty

r_packages:
  - testthat
  - covr

r_github_packages:
  - greta-dev/greta
  - goldingn/gpflowr

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - libmagick++-dev
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - python-dev
      - libv8-dev

before_install:
  - pip install --upgrade pip
  - pip install --user numpy
  - pip install --user tensorflow
  - git clone https://github.com/GPflow/GPflow.git
  - cd GPflow
  - sudo python setup.py install
  - cd ..

after_success:
  - Rscript -e "gpflowr::gpflow_available()"
  - Rscript -e "(cov <- covr::package_coverage()); covr::codecov(coverage = cov)"

email:
  on_success: change
  on_failure: change
